//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.07 at 04:07:08 PM CEST 
//


package xbrl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.inteco.es/xbrl/pgc07/interfazES}item" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.inteco.es/xbrl/pgc07/interfazES}record" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.inteco.es/xbrl/pgc07/interfazES}table" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="reportingDateStart" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="reportingDateEnd" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="baseUnit" type="{http://www.inteco.es/xbrl/pgc07/interfazES}unittype" default="string" />
 *       &lt;attribute name="baseDecimals" type="{http://www.w3.org/2001/XMLSchema}string" default="0" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "item",
    "record",
    "table"
})
@XmlRootElement(name = "module")
public class Module {

    protected List<Item> item;
    protected List<Record> record;
    protected List<Table> table;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "reportingDateStart", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar reportingDateStart;
    @XmlAttribute(name = "reportingDateEnd", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar reportingDateEnd;
    @XmlAttribute(name = "baseUnit")
    protected Unittype baseUnit;
    @XmlAttribute(name = "baseDecimals")
    protected String baseDecimals;

    /**
     * Gets the value of the item property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the item property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Item }
     * 
     * 
     */
    public List<Item> getItem() {
        if (item == null) {
            item = new ArrayList<Item>();
        }
        return this.item;
    }

    /**
     * Gets the value of the record property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the record property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRecord().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Record }
     * 
     * 
     */
    public List<Record> getRecord() {
        if (record == null) {
            record = new ArrayList<Record>();
        }
        return this.record;
    }

    /**
     * Gets the value of the table property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the table property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTable().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Table }
     * 
     * 
     */
    public List<Table> getTable() {
        if (table == null) {
            table = new ArrayList<Table>();
        }
        return this.table;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the reportingDateStart property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReportingDateStart() {
        return reportingDateStart;
    }

    /**
     * Sets the value of the reportingDateStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReportingDateStart(XMLGregorianCalendar value) {
        this.reportingDateStart = value;
    }

    /**
     * Gets the value of the reportingDateEnd property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReportingDateEnd() {
        return reportingDateEnd;
    }

    /**
     * Sets the value of the reportingDateEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReportingDateEnd(XMLGregorianCalendar value) {
        this.reportingDateEnd = value;
    }

    /**
     * Gets the value of the baseUnit property.
     * 
     * @return
     *     possible object is
     *     {@link Unittype }
     *     
     */
    public Unittype getBaseUnit() {
        if (baseUnit == null) {
            return Unittype.STRING;
        } else {
            return baseUnit;
        }
    }

    /**
     * Sets the value of the baseUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Unittype }
     *     
     */
    public void setBaseUnit(Unittype value) {
        this.baseUnit = value;
    }

    /**
     * Gets the value of the baseDecimals property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseDecimals() {
        if (baseDecimals == null) {
            return "0";
        } else {
            return baseDecimals;
        }
    }

    /**
     * Sets the value of the baseDecimals property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseDecimals(String value) {
        this.baseDecimals = value;
    }

}
