//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.07 at 04:07:08 PM CEST 
//


package xbrl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for unittype.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="unittype">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="euro"/>
 *     &lt;enumeration value="shares"/>
 *     &lt;enumeration value="pure"/>
 *     &lt;enumeration value="string"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "unittype")
@XmlEnum
public enum Unittype {

    @XmlEnumValue("euro")
    EURO("euro"),
    @XmlEnumValue("shares")
    SHARES("shares"),
    @XmlEnumValue("pure")
    PURE("pure"),
    @XmlEnumValue("string")
    STRING("string");
    private final String value;

    Unittype(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Unittype fromValue(String v) {
        for (Unittype c: Unittype.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
